### ISSUE TITLE
✨ [Feature] 게시물 상세 조회 API

### ISSUE THREAD

**Issue by ooheunda** [wanted-pre-ob/social-feed-hub#13]
### Description

**`GET /api/postings/:id`**  
게시물의 상세를 조회할 수 있습니다. `posting` 테이블의 PK(uuid)를 경로 변수로 받습니다.  
이 API 요청 시 게시물의 조회 수가 1씩 증가합니다.

### Todo

- [x] 게시물의 `view_count` 1 증가
- [x] 예외처리
  - [x] `404` 경로 변수에 해당하는 게시물이 존재하지 않는 경우
  - [x] `401` 인증되지 않은 사용자의 접근인 경우 (가드 사용)

#### ❓ 게시물 상세 조회 API는 일반적으로 `GET` method를 사용하는데, 해당 API는 조회뿐 아니라 조회수 증가라는 데이터 변경 작업도 함께 하고 있어, `PATCH`를 써야할 지 고민됩니다.
*(23일 회의에서 논의 및 해결된 내용)*  
- `GET` 사용 시: 직관적이고 실용적이나 멱등성에 위반됨
- `PATCH` 사용 시: RESTful API 원칙에는 만족하나 직관적이지 않음
- 제 3의 의견: API 두 개로 세분화(상세 조회/조회수 증가) -> client 측에서 실수할 가능성 고려 & 호출 비용 증가
- **결론**: 실용성을 중시해 `GET`으로 결정
