### ISSUE TITLE
✨ [Feature] 게시글 좋아요 API 

### ISSUE THREAD

**Issue by joosomi** [wanted-pre-ob/social-feed-hub#15]
### Description

**`PATCH /api/postings/:id/like`**
특정 게시글에 좋아요 버튼을 클릭할 수 있습니다. 
`Posting` 테이블의 PK인 id를 path variable로 받습니다.
버튼을 클릭하면 `like_count`가 1 증가합니다. (횟수 제한이 없습니다.)

### Todo

- [x] like_count 1 증가 처리
- [x] 성공시 204 처리 
- [ ] 예외 처리
   - [ ]  401: 인증 권한 처리 - 좋아요를 할 수 없습니다. 
   - [x]  404: 존재하지 않는 게시글입니다.
- [ ] Swagger 

- 다 구현한다면 
   - 좋아요 횟수 제한 로직 고민해보기

### ETC

Too many request나 마지막 액션 시간 저장하고 일정 시간 지나지 않으면 요청 거부한다는 등 과도한 클릭 방지 로직 생각해보기 !
