### ISSUE TITLE
✨ [Feature] 게시글 공유 API

### ISSUE THREAD

**Issue by joosomi** [wanted-pre-ob/social-feed-hub#16]
### Description

**`PATCH /api/postings/:id/share`**
특정 게시글 공유하기 버튼 클릭시 사용되는 API 
Posting 테이블의 PK인 `id`를 path variable로 받습니다.
버튼을 클릭하면 `share_count`가 1 증가합니다. (횟수 제한이 없습니다.)

### Todo

- [x] `posting` table - `share_count` 1 증가
- [x] 성공시 204 처리
- [ ] 예외 처리
   - [ ] 401: 인증 권한 처리 - 공유할 수 없습니다.
   - [x] 404: 존재하지 않는 게시글입니다.
-  [ ] Swagger
